# Generated by Django 2.2.3 on 2019-08-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_name', models.TextField()),
                ('epithet_name', models.TextField()),
                ('common_name', models.TextField()),
                ('max_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesOccurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VegetationLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.PositiveIntegerField(choices=[(1, 'K'), (2, 'S2'), (3, 'S1'), (4, 'B2'), (5, 'B1')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billboard', models.TextField()),
                ('vegetation_layer', models.PositiveIntegerField(choices=[(1, 'K'), (2, 'S2'), (3, 'S1'), (4, 'B2'), (5, 'B1')], default=None)),
                ('distribution_type', models.PositiveIntegerField(choices=[(1, 'Random'), (2, 'Clumping')], default=1)),
                ('distribution_density', models.FloatField(default=1)),
                ('avg_height', models.FloatField()),
                ('sigma_height', models.FloatField()),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assetpos.Asset')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vegetation.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Phytocoenosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('albedo_path', models.TextField(null=True)),
                ('normal_path', models.TextField(null=True)),
                ('heightmap_detail_path', models.TextField(null=True)),
                ('speciesRepresentations', models.ManyToManyField(to='vegetation.SpeciesRepresentation')),
            ],
        ),
    ]
