# Generated by Django 2.1.5 on 2019-03-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytocoenosis',
            old_name='bumpmap_path',
            new_name='normal_path',
        ),
    ]
