# Generated by Django 2.1.5 on 2020-04-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytocoenosis',
            old_name='heightmap_detail_path',
            new_name='displacement_path',
        ),
    ]
