# Generated by Django 2.1.5 on 2019-04-29 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import location.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857)),
                ('viewport', django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('direction', models.FloatField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bounding_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[(location.models.ServiceChoice('Digital Height Model'), 'Digital Height Model'), (location.models.ServiceChoice('Orthophotos'), 'Orthophotos'), (location.models.ServiceChoice('Buildings'), 'Buildings'), (location.models.ServiceChoice('Map Tiles'), 'Map Tiles'), (location.models.ServiceChoice('Trees / Forests'), 'Trees / Forests')], max_length=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='location.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='location.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Scenario'),
        ),
        migrations.AddField(
            model_name='location',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='location.Scenario'),
        ),
        migrations.AddField(
            model_name='impression',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Session'),
        ),
    ]
