# Generated by Django 2.0.5 on 2018-12-13 13:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('viewport', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bounding_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('workshop', models.TextField(blank=True, default=None, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Session'),
        ),
    ]
