# Generated by Django 2.1.7 on 2019-02-24 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direction', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='start_location',
        ),
        migrations.AddField(
            model_name='scenario',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Location'),
        ),
    ]
