# Generated by Django 2.1.5 on 2019-04-02 18:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190224_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('date', models.DateTimeField()),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Scenario')),
            ],
        ),
    ]
