# Generated by Django 2.2.1 on 2019-09-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190728_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='energy_requirement_summer',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='energy_requirement_winter',
        ),
    ]
