# Generated by Django 2.1.5 on 2019-04-12 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import location.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[(location.models.ServiceChoice('Digital Height Model'), 'Digital Height Model'), (location.models.ServiceChoice('Orthophotos'), 'Orthophotos'), (location.models.ServiceChoice('Buildings'), 'Buildings'), (location.models.ServiceChoice('Trees / Forests'), 'Trees / Forests')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='location.Service')),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='scenario',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='start_location',
        ),
        migrations.RemoveField(
            model_name='session',
            name='workshop',
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='location.Scenario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.AddField(
            model_name='service',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='location.Scenario'),
        ),
        migrations.AddField(
            model_name='map',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Scenario'),
        ),
    ]
