# Generated by Django 2.1.7 on 2019-03-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='assetpos.AssetType'),
            preserve_default=False,
        ),
    ]
