# Generated by Django 2.1.5 on 2019-04-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpositions',
            name='tile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raster.Tile'),
        ),
    ]
