# Generated by Django 2.1.5 on 2019-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0002_auto_20190430_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='allow_placement',
            field=models.BooleanField(default=False),
        ),
    ]
