# Generated by Django 2.1.5 on 2019-04-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0002_asset_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetpos.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identfier', models.TextField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetpos.AssetType')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetpos.Property'),
        ),
    ]
