# Generated by Django 2.1.5 on 2019-04-12 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0003_auto_20190402_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='identfier',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='assettype',
            name='placement_areas',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='assetpos.Asset'),
        ),
    ]
