# Generated by Django 2.2.3 on 2019-08-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0003_assettype_allow_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='display_radius',
            field=models.IntegerField(default=0),
        ),
    ]
