# Generated by Django 2.2.4 on 2019-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0004_assettype_display_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='minimum_distance',
            field=models.IntegerField(default=0),
        ),
    ]
