# Generated by Django 2.2.4 on 2019-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0005_assettype_minimum_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpositions',
            name='orientation',
            field=models.FloatField(default=0),
        ),
    ]
