# Generated by Django 2.2.4 on 2019-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0006_auto_20190819_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettype',
            name='abstract',
            field=models.BooleanField(default=False),
        ),
    ]
