# Generated by Django 2.2.1 on 2019-09-07 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0008_assettype_energy_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='energy_target',
        ),
        migrations.AddField(
            model_name='asset',
            name='energy_multiplicator',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='assetpositions',
            name='create_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
