# Generated by Django 2.2.4 on 2019-08-19 21:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('width', models.FloatField()),
                ('display_radius', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('width', models.FloatField(null=True)),
                ('tile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='raster.Tile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='linear.LineType')),
            ],
        ),
    ]
