# Generated by Django 2.1.7 on 2019-03-02 14:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='heightmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=256), blank=True, null=True, size=256),
        ),
        migrations.AlterField(
            model_name='tile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='raster.Tile'),
        ),
    ]
