# Generated by Django 2.1.7 on 2019-03-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0002_auto_20190302_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='raster.Tile'),
            preserve_default=False,
        ),
    ]
