# Generated by Django 2.1.7 on 2019-03-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0003_auto_20190303_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='raster.Tile'),
        ),
    ]
