# Generated by Django 2.1.5 on 2019-04-02 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0004_auto_20190304_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalheightmodel',
            name='resolution',
            field=models.FloatField(default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='watersplatmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=256), blank=True, null=True, size=256),
        ),
    ]
