# Generated by Django 2.1.5 on 2019-04-29 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetpos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertices', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('height', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetpos.AssetPositions')),
            ],
        ),
    ]
