# Generated by Django 2.1.7 on 2019-02-24 18:00

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.contrib.gis.geos.polygon
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetpos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertices', django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(django.contrib.gis.geos.linestring.LinearRing([(-1, -1), (1, -1), (1, 1), (-1, 1), (-1, -1)])), srid=4326)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetpos.AssetPositions')),
            ],
        ),
    ]
