# Generated by Django 2.1.7 on 2019-03-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0002_asset_asset_type'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingLayout',
            new_name='BuildingFootprint',
        ),
    ]
