# Generated by Django 2.1.5 on 2019-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfootprint',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
