# Generated by Django 2.1.5 on 2019-04-12 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20190328_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingfootprint',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetpos.AssetPositions'),
        ),
        migrations.AlterField(
            model_name='buildingfootprint',
            name='vertices',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
