# Generated by Django 2.0.3 on 2019-09-08 23:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetpos', '0009_auto_20190907_2222'),
        ('location', '0004_remove_scenario_energy_requirement_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetpositionToEnergylocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_position', to='assetpos.AssetPositions')),
                ('energy_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_location', to='assetpos.AssetPositions')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('energy_production', models.FloatField()),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetpos.AssetType')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(default=0)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetpos.AssetType')),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Scenario')),
            ],
        ),
    ]
