# Generated by Django 2.2.4 on 2019-09-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetpos', '0009_auto_20190907_2222'),
        ('energy', '0002_auto_20190913_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='energylocation',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetpos.Asset'),
        ),
    ]
